version: "3"
services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    ports:
      - "27017:27017"

  api:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
